---
- hosts: all
  vars:
    web_network: "web"
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker APT repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        state: present

    - name: Install required apt packages
      apt:
        name:
          - python3-pip
          - apt-transport-https
          - curl
          - software-properties-common
          - docker-ce
        update_cache: true

    - name: Install required python packages
      pip:
        name:
          - docker

    - name: Ensure docker-py python package is not installed (clashes with docker package)
      pip:
        name:
          - docker-py
        state: absent

    - name: Ensure journald is running
      systemd:
        name: systemd-journald
        state: started
        enabled: true

    - name: Create traefik directory
      file:
        path: /opt/traefik
        state: directory

    - name: Copy over traefik config
      template:
        src: traefik.toml.tpl
        dest: /opt/traefik/traefik.toml

    - name: Create acme.json placeholder
      copy:
        content: ""
        dest: /opt/traefik/acme.json
        force: no
        mode: "600"

    - name: Create web network
      docker_network:
        name: "{{web_network}}"
        state: present

    - name: Launch Traefik container
      docker_container:
        name: traefik
        image: traefik
        state: started
        restart_policy: always
        ports:
          - 80:80
          - 443:443
        env:
          DO_AUTH_TOKEN: "{{do_auth_token}}"
        purge_networks: true
        networks:
          - name: "{{web_network}}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /opt/traefik/traefik.toml:/traefik.toml
          - /opt/traefik/acme.json:/acme.json

    - name: Launch Jenkins container
      docker_container:
        name: jenkins
        image: "jenkinsci/blueocean:1.14.0"
        state: started
        restart_policy: always
        exposed_ports:
          - "8080"
          - "50000"
        labels:
          traefik.enable: "true"
          traefik.port: "8080"
          traefik.frontend.rule: "Host:jenkins.{{domain}}"
          traefik.docker.network: "{{web_network}}"
        purge_networks: true
        networks:
          - name: "{{web_network}}"
        volumes:
          - /var/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        user: root
